export default {
  JSE001: "Please select %s",
  JSE002: "%s is greater than %s!",
  JSE003: "Delete Successfully!",
  JSE004: "Please choose you want to Delete!",
  JSE005: "Please fill %s!",
  JSE007: "%s is already exists!",
  JSE009: "The number of files has exceeded.Maximum upload files limit is 2!", // 20
  JSE010: "Please fill Leave Name English Character Only!",
  JSE011: "%s is greater than 100!",
  JSE012: "Please fill %s is between 0 to 1!",
  JSE013: "Please fill %s English Number Only!",
  JSE014: "%s is greater than %s!",
  JSE015: "%s is greater than 60 minutes!",
  JSE016: "Please fill %s Positive Number Only!",
  JSE017: "%s is less than %s!",
  JSE018: "Please fill %s!",
  JSE019: "Please choose %s!",
  JSE020: "Please choose %s Only!",
  JSE021: "Please choose you want to Delete!",
  JSE022: "Duplicate files are not allowed!",
  JSE023: "%s and %s should not be same!",
  JSE024: "This file type is not supported",
  JSE025: "Please choose %s or remove %s",
  JSE026: "%s is number only!",
  JSE027: "%s is at least %s",
  JSE028: "Invalid %s!",
  JSE029: "Incorrect %s!",
  JSE030: "Please fill number from %s to %s!",
  JSE031: "%s label type needs at least one add field label!",
  JSE032: "Duplicate %s %s are not allowed!",
  JSE033: "%s must be less than %s characters!",
  JSE034: "%s is already taken!",
  JSE035: "You need to create %s with at least %s!"
};
